language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install --dev --prefer-source --no-interaction

script: ./vendor/bin/phpunit
